Create VeFunds
vechain/grant-program pull request #154
Opened 2023-06-04 17:12 UTC by Emma66886

# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-06-20 05:48 UTC, libotony requested changes

2023-06-20 05:48 UTC, libotony commented on applications/VeFunds.md
> +|  | Milestone 1 | Milestone 2 | Total |
```suggestion
|  | Milestone 1 | Milestone 2 | Milestone 3 | Total| 
```

2023-06-20 05:48 UTC, libotony commented on applications/VeFunds.md
> +-Third Milestone(Platform full lunch and maintenance)
```suggestion
- Third Milestone(Platform full lunch and maintenance)
```

2023-06-20 05:48 UTC, libotony commented on applications/VeFunds.md
> +...
Please complete the full milestone info, based on your application there are three milestones.

2023-06-20 17:24 UTC, Emma66886 commented
Thanks @libotony the requested changes has been updated accordingly. Thanks.

2023-06-21 03:04 UTC, libotony commented on applications/VeFunds.md
> +| Cost ($ 15,000) | $ 9,000 | $ 1,000 | $ 5,000|
This should be table and the last row should be the total cost.

2023-06-21 03:05 UTC, libotony commented on applications/VeFunds.md
> +...
This line should be removed.

2023-06-21 09:59 UTC, Emma66886 commented
Changes has been updated. Kindly review it

2023-06-24 13:02 UTC, Emma66886 commented
Hello @libotony ,How are you doing? 
Just checking back on the changes you requested.

2023-06-26 05:50 UTC, libotony commented
> Hello @libotony ,How are you doing? Just checking back on the changes you requested.

@Emma66886 Please take a look at https://github.com/vechain/grant-program/pull/154#discussion_r1236226777, this needs to be updated

2023-06-26 09:26 UTC, Emma66886 commented
> > Hello @libotony ,How are you doing? Just checking back on the changes you requested.
> 
> @Emma66886 Please take a look at [#154 (comment)](https://github.com/vechain/grant-program/pull/154#discussion_r1236226777), this needs to be updated

Apologies  @libotony I have made change on the request. Thanks

2023-06-27 06:57 UTC, libotony requested changes

2023-06-27 06:57 UTC, libotony commented on applications/VeFunds.md
> +| Cost (up to $ 15,000)| $ 9,000 | $ 1,000 | $ 5,000 | $ 15,0000 |
```suggestion
| Cost (up to $ 15,000)| $ 9,000 | $ 1,000 | $ 5,000 | $ 15,000 |
```

2023-06-27 10:59 UTC, Emma66886 commented
Changes  @libotony  committed

2023-07-27 08:09 UTC, Emma66886 commented
Hello @libotony just checking back, any response from the team?

2023-07-27 08:13 UTC, libotony commented
> Hello @libotony just checking back, any response from the team?

This application is in the review stage, which means it is awaiting review by the committee. We'll get back to you after we collected all votes from the committee.

2023-08-23 06:56 UTC, closed without merging