Adding VeFarm proposal
vechain/grant-program pull request #161
Opened 2023-07-17 07:56 UTC by fede-rodes

# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-07-28 06:44 UTC, libotony requested changes

2023-07-28 06:44 UTC, libotony commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
Hi, we only accept USDC as our mode of payment. Could you possibly convert the VTHO amount into its equivalent value in USD?

2023-07-28 07:01 UTC, libotony commented
Thank you for submitting your application. After a careful review of your application, I have a few questions regarding user funds security:

+ Do you have a plan for auditing the contract?
+ Since the user approved unlimited VTHO approval, how to secure users funds?
+ Will DEX's contract address hardcoded in contract?

2023-07-30 22:45 UTC, fede-rodes commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
Hi, I just checked the price of VTHO, and 5,000 VTHO is about 5 USD. So, I'll simply remove the VTHO from the equation and assume it's covered by the USD amount I already set. Thanks!

2023-07-31 07:11 UTC, libotony commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
@fede-rodes Thanks for the quick response, I just made a rough calculation, $2500 could buy around `2,000,000 VTHO`, I would suggest updating the fee delegation amount to the equivalent value, you could put a rough estimation since the price of VTHO may change.

2023-07-31 07:13 UTC, libotony commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
I might misunderstand your point, I would suggest removing the comment in milestone.

2023-07-31 10:06 UTC, fede-rodes commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
Hi @libotony ,

First of all, let me thank you for reviewing the application. I was planning on doing so on the other thread later today, but in the end, I didn't have the time to finish writing the answer to your questions. So, thank you!

With that said, let me try to clarify the quote for milestone 3. The plan is to allocate $2,500 to cover the man-hours costs. In milestone 3, I intend to set up a production environment for both front and backend, deploy the smart contract to production, conduct thorough testing, engage with the community, and handle any unforeseen tasks that may arise. I'm hoping that $2,500 is a reasonable amount to cover all these activities.

On the other hand, during the initial phase of the project, the plan is to enable fee delegation. That's why I included 5,000 VTHO in the budget for milestone 3. Assuming a transaction cost of 5 VTHO, this should be sufficient to cover around 1,000 transactions.

After reading your first comment, I looked into the price of VTHO, and since it's negligible, I decided to remove the VTHO from the equation and incorporate this cost within the $2,500 budget. I hope this clears things up.

Let me know if you still want me to remove the comment in milestone 3. Thanks

2023-07-31 11:47 UTC, libotony commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
> First of all, let me thank you for reviewing the application. I was planning on doing so on the other thread later today, but in the end, I didn't have the time to finish writing the answer to your questions. So, thank you!

No hurry, please take your time.

2023-07-31 11:52 UTC, libotony commented on applications/veFarm.md
> +| Cost (up to $ 30,000) | $ 5,000 (done) | $ 5,000 | $ 2,500 + 5,000 VTHO | $ 12,500 + 5,000 VTHO |
I fully understand your comment regarding `2500VTHO can be covered by a small amount of USD so removed it`. I am just suggesting removing the comment `(this amount covers the cost of 5,000 VTHO tokens allocated for fee delegation)`, since the review committee might be confused about the comment, they might only be interested in what's in milestone 3 and how much is the cost for milestone 3, feel free to leave this unchanged if you want to explain to the review committee.

2023-08-01 02:44 UTC, fede-rodes commented
Hi @libotony 

Here are the answers to your questions. Looking forward to your reply. Thanks

- Do you have a plan for auditing the contract?

Unfortunately, I lack of funds to afford a professional audit. Instead, my plan is to share the contract with colleagues and the VeChain and Solidity programmers community on Discord and Twitter. Additionally, I would gladly share it with any interested VeChain core programmers, if they have the time for it.
    
- Will DEX's contract address hardcoded in contract?

In short, yes, we'll hardcode the addresses, and if the need arises to add more DEXs, we will deploy a new contract. Initially, when I wrote the application, I thought that we could add more DEXs via a multisig wallet, but now it seems like overkill. As a result, I'll need to update that part of the proposal where I mention "Integrate a list of accessible DEXs for trading, alongside restricted functions to add or remove them." Thanks for pointing this out.

- Since the user approved unlimited VTHO approval, how to secure users funds?

Below is a list of features I plan to implement to enhance the contract's security (I should probably add these comments to the application itself):

1. The contract will remain non-upgradable and open-source, allowing anyone to verify its logic (although, to the best of my knowledge, VeChain contracts cannot be publicly verified via any VeChain Explorer; please correct me if I'm wrong).

2. Access to the swap function will be limited, likely restricted to the contract's owner and some admin accounts (TBD).

3. The contract is designed to be non-custodial, ensuring that users' funds stay in their accounts until the swap function is executed. Once triggered, the funds will be transferred from the user's account to the VeFarm contract, then to the DEX contract, and finally back to the user account, all in a single atomic operation (this clarification should be made in the "Blockchain Level Interaction Flow" section of the document).

Now, if we approach the question from a different perspective, let's consider a scenario where I act as a bad actor or lose control over my private keys.

In such a case, I am contemplating the potential impact on the user. One concern is that the attacker might maliciously trigger the swap function more frequently than necessary. This could result in the user incurring higher fees and receiving fewer VET tokens, or even receiving none at all. However, the attacker would not gain any benefit from such actions since the protocol's fee generation would diminish.

Another potential concern arises when assuming a large swap amount, and the attacker sets an overly high `minRate` value (high slippage). In this scenario, the attacker could submit the `swap` transaction, along with transactions before and after the swap, causing a "sandwich" attack that trades at a significantly worse price, profiting at the user's expense. For this to happen, the attacker would need to have access to a flash loan and/or wait for low liquidity on a DEX. Unfortunately, VeChain does not support on-chain Oracles (to the best of my knowledge), making it impossible to remove the `minRate` parameter.

To safeguard users from the aforementioned potential risks, we can implement certain measures. One approach would involve removing the `amountIn` parameter from the `swap` function and prompting the user to set a VTHO amount target that triggers the swap function once their account balance reaches the specified threshold. For example, a user could set a trigger like "execute a swap when my account balance reaches 1000 VTHO." This target should be stored in the contract and verified when the swap function is triggered; otherwise, the transaction would revert. This measure would prevent an attacker with owner or admin privileges from repeatedly calling the swap function to harm the user. The downside of this change is that the mathematical analysis might not be feasible. However, despite its importance in the protocol, I am willing to modify the proposal if it leads to a more secure protocol and benefits the user. Ultimately, the goal is to enable users to swap VTHO for VET securely.

Regarding the second potential risk, the sandwich attack, we could introduce an upper bound in the contract itself to limit the maximum amount of VTHO being swapped.

2023-08-01 10:03 UTC, libotony commented
Thank you for the comprehensive explanation, I would suggest verifying the contract even explorer does not provide the functionality. By the way, this application is great for community members.

2023-08-01 21:31 UTC, fede-rodes commented
Thanks for your answer, @libotony . Do you mind if I update the proposal with some of the comments I pointed out in my previous message and squash all the commits? Thanks

2023-08-02 02:46 UTC, libotony commented
> Thanks for your answer, @libotony . Do you mind if I update the proposal with some of the comments I pointed out in my previous message and squash all the commits? Thanks

Sure, proceed please.

2023-09-08 23:52 UTC, fede-rodes commented
Hi @NecoSherry @libotony  just for the record, I wanted to share my of the progress so far. I know other project in the ecosystem is building something very similar and I hope this doesn't affect my chances to get the grant and being able to keep building in the VeChain ecosystem. Thanks

![image](https://github.com/vechain/grant-program/assets/16927407/05bc2766-b057-4275-9882-9026bd6f3fe2)
![image](https://github.com/vechain/grant-program/assets/16927407/b93a44a6-dc4c-4762-a5df-d19239340397)
![image](https://github.com/vechain/grant-program/assets/16927407/1ff776d5-1f1b-40df-8552-5b06c5872f09)
![image](https://github.com/vechain/grant-program/assets/16927407/d119df71-e136-48da-8d6f-d35e6e572de5)
![image](https://github.com/vechain/grant-program/assets/16927407/acf22697-a935-4b01-bf10-80df39b01d53)

2023-10-16 21:50 UTC, fede-rodes commented
Hi @NecoSherry and @libotony, a quick update from my side. I've managed to develop a mathematical algorithm to optimize the timing of swaps based on the account balance and market conditions (transaction fee and exchange rate). As a result, the user only needs to set the 'reserve balance,' which is the amount of VTHO they would like to retain in the wallet after the swap(s), and the protocol will search for the 'optimal' amount of VTHO that, when reached, will trigger a new swap. This maximizes the amount of VET accumulated by the account. Thanks

![Screenshot from 2023-10-17 09-16-58](https://github.com/vechain/grant-program/assets/16927407/32800457-cb53-442a-8ccf-41037067c13f)
![Screenshot from 2023-10-17 09-17-46](https://github.com/vechain/grant-program/assets/16927407/ba261138-d597-4891-9da7-27ccc63b6301)
![Screenshot from 2023-10-17 10-41-43](https://github.com/vechain/grant-program/assets/16927407/bb290b90-ebe4-4368-aef7-87594d509967)

2023-10-18 08:00 UTC, NecoSherry commented
Congratulations! Your application has been accepted by the committee!

We would like to inform you that we have recently updated our payment currency to USDC (ERC 20). Therefore, we kindly ask you to confirm that your payment address is capable of receiving USDC payments. 

In order to proceed with further payments, we need to contact with you through email. Please send an email to [grant@vechain.org](mailto:grant@vechain.org) with your project name, PR link and payment address (same as in the PR).

2023-10-18 08:14 UTC, libotony approved these changes

2023-10-18 08:32 UTC, merged

2023-10-18 14:01 UTC, fede-rodes commented
AWESOME!!! :confetti_ball:  :partying_face: 

Thanks a lot for the support. :pray: