Create VeBlocks_NodeAccess_2023.md
vechain/grant-program pull request #176
Opened 2023-08-21 21:49 UTC by mirei83

# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-09-01 07:36 UTC, libotony requested changes

2023-09-01 07:36 UTC, libotony commented on applications/VeBlocks_NodeAccess_2023.md
> +- Project: VeBlocks free access to public Vechain blockchain nodes
According to the rules of our program, kindly ensure that the project name and the file name are identical.

2023-09-01 07:36 UTC, libotony commented on applications/VeBlocks_NodeAccess_2023.md
> +- Payment Address: 0xcb0c81cf6742c2ea97cec01f95c08d22045edbfc USDT (ERC 20)
Our payment method has been updated to “USDC”. We kindly request you to verify this change.

2023-10-18 08:01 UTC, NecoSherry approved these changes
Congratulations! Your application has been accepted by the committee!

We would like to inform you that we have recently updated our payment currency to USDC (ERC 20). Therefore, we kindly ask you to confirm that your payment address is capable of receiving USDC payments.

In order to proceed with further payments, we need to contact with you through email. Please send an email to [grant@vechain.org](mailto:grant@vechain.org) with your project name, PR link and payment address (same as in the PR).

2023-10-18 08:14 UTC, libotony approved these changes

2023-10-18 08:32 UTC, merged