Gamifly_grant program
vechain/grant-program pull request #180
Opened 2023-09-12 10:58 UTC by AylabCompany

# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-11-08 10:54 UTC, libotony requested changes

2023-11-08 10:54 UTC, libotony commented on applications/Gamifly
> +# VeChain General Grant Application Template
Filename should be `xxx.md`

2023-11-08 11:03 UTC, robertzhangwei approved these changes

2024-01-25 04:01 UTC, NecoSherry commented
We have launched a new grant, and this repository is no longer accepting new applications. If you would like to submit a revised application, please visit https://www.vechain.org/grant-program. Therefore, I will be closing this PR.

2024-01-25 04:01 UTC, closed without merging