Create onchainvision.md
vechain/grant-program pull request #181
Opened 2023-09-18 16:47 UTC by raldblox

# Grant Application Checklist

- [X] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] An Ethereum address for the payment of the milestones is provided inside the application.  
- [X] The total funding amount of the project is up to USD $30k for every grant applications.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-12-06 08:10 UTC, libotony requested changes

2023-12-06 08:10 UTC, libotony commented on applications/onchainvision.md
> +
https://github.com/vechain/grant-program/blob/master/applications/application-template.md#overview-1 We have a rule that limits milestone 1 funds should not be higher than 40% of the total amount you are applying for, I would suggest adding more milestones.

2023-12-06 08:10 UTC, libotony commented on applications/onchainvision.md
> +
[ETH Research Grants funding for Cutting-Edge Ethereum Studies](https://dorahacks.io/buidl/6643?badge=b5652) provided additional details and use-cases, strengthening the project’s presentation. Could you update the information here as well to assist the review committee in understanding the project better

2024-01-25 04:02 UTC, NecoSherry commented
We have launched a new grant, and this repository is no longer accepting new applications. If you would like to submit a revised application, please visit https://www.vechain.org/grant-program. Therefore, I will be closing this PR.

2024-01-25 04:02 UTC, closed without merging