cosmoly proposal
vechain/grant-program pull request #187
Opened 2023-10-02 05:13 UTC by AgentDavid

# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-10-27 04:23 UTC, laalaguer commented
Hi, in the middle the "budget" part the table is mangled, could you please correct it?

2023-10-27 09:12 UTC, AgentDavid commented
correction made, I am attentive to any comments

2023-12-07 08:14 UTC, libotony requested changes

2023-12-07 08:14 UTC, libotony commented on applications/cosmoly.md
> +|  | Milestone 1 | Milestone 2 | Total |
https://github.com/vechain/grant-program/blob/master/applications/application-template.md#overview-1 We have a rule that limits milestone 1 funds should not be higher than 40% of the total amount you are applying for, I would suggest splitting milestone1 into 2 milestones, thank you in advance!

2023-12-07 08:14 UTC, libotony commented on applications/cosmoly.md
> +#### Benefits of working with VeChain Services
Could you provide the transaction stats of your platform? This would greatly benefit the committee in their review of the project.

2024-01-25 04:02 UTC, NecoSherry commented
We have launched a new grant, and this repository is no longer accepting new applications. If you would like to submit a revised application, please visit https://www.vechain.org/grant-program. Therefore, I will be closing this PR.

2024-01-25 04:02 UTC, closed without merging