Flybloc Grant Application
vechain/grant-program pull request #212
Opened 2023-11-22 22:02 UTC by FlyblocDev

# Grant Application Checklist

- [ ] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ ] The total funding amount of the project is up to USD $30k for every grant applications.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

2023-12-01 07:50 UTC, libotony commented
Thank you for moving your application to the appropriate folder. However, you are still using the template for the general grant. Could you please adjust your application to align with the [EasyA Grant Track template](https://github.com/vechain/grant-program/blob/90ca36f2c30758b4690ceaf9ff3ef9da9f4363fa/Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/FibreTag.md)?

Please avoid opening a new pull request if possible. Instead, submit a new commit within this existing pull request to update your application. Thank you for your cooperation.

2023-12-01 07:52 UTC, libotony commented on applications/Flybloc.md
> +- [Project’s one-pager](https://drive.google.com/file/d/1-XyiktDbbNv989igzI_MBvY1fkbqWTZf/view?usp=drive_link) (provided by BCG at the Hackathon)
I have requested document access for the account `tony.li@vechain.org`, please kindly check your inbox and give read access to that account.

2023-12-06 04:55 UTC, libotony requested changes
Please adjust your application to align with the [EasyA Grant Track template](https://github.com/vechain/grant-program/blob/90ca36f2c30758b4690ceaf9ff3ef9da9f4363fa/Vechain-EasyA-Hackathon-Boston-Oct-2023/applications/FibreTag.md)

2023-12-11 02:27 UTC, libotony commented
@FlyblocDev Thank you for the update, but your application seems to be in the folder of the general grant application. Please consider moving to folder [Vechain-EasyA-Hackathon-Boston-Oct-2023](https://github.com/vechain/grant-program/tree/master/Vechain-EasyA-Hackathon-Boston-Oct-2023/applications).

2024-01-19 06:01 UTC, NecoSherry commented
Thank you for your interest in our grant program and for submitting your application. We regret to inform you that your application has been rejected by the grant committee. 

The main reason is that your application lacks sufficient description regarding how it supports brands and its profitability through its business model. 

I’m therefore closing the PR.  In any case, we thank you for your interest in the grant program.

2024-01-19 06:01 UTC, closed without merging