Add deliveries of leaderless BFT consensus protocol
vechain/grant-program pull request #230
Opened 2024-02-24 04:43 UTC by gitferry

This PR added all the deliveries of the application [leaderless-bft-consensus](https://github.com/vechain/grant-program/blob/master/applications/leaderless_bft_consensus.md).

2024-02-27 02:55 UTC, zzGHzz approved these changes

2024-02-27 03:31 UTC, libotony requested changes

2024-02-27 03:31 UTC, libotony commented on accepted_grant_applications.md
> +| --- | :-: | :-: | :-: | :-: | :-: |:----------------------------------:|
```suggestion
| Project | Category | Link | Funds | First Delivery | Completed | Milestone Status |
| --- | :-: | :-: | :-: | :-: | :-: |:-:|
```

2024-02-27 03:31 UTC, libotony commented on accepted_grant_applications.md
> +| [An institutional map of VeChain governance](https://github.com/vechain/grant-program/blob/master/applications/map-of-vechain-governance.md) | Research  | [Applicantion](https://github.com/vechain/
```suggestion
| [An institutional map of VeChain governance](https://github.com/vechain/grant-program/blob/master/applications/map-of-vechain-governance.md) | Research  | [Applicantion](https://github.com/vechain/grant-program/blob/master/applications/map-of-vechain-governance.md)  | $29,646 | ✅ |   | ![](https://geps.dev/progress/33) |
```

2024-02-27 03:31 UTC, libotony commented on accepted_grant_applications.md
> +| [Digital Village](https://github.com/vechain/grant-program/blob/master/applications/digital-village.md) | NFT Marketplace |  [Website](https://digitalvillage.io/) | $30,000 |   |   |  ![](https://g
```suggestion
| [Digital Village](https://github.com/vechain/grant-program/blob/master/applications/digital-village.md) | NFT Marketplace |  [Website](https://digitalvillage.io/) | $30,000 |   |   | ![](https://geps.dev/progress/0) |
```

2024-02-27 03:31 UTC, libotony commented on accepted_grant_applications.md
> +| [Village Protocol](https://github.com/vechain/grant-program/blob/master/applications/village-protocol.md) | Social Media |  [Website](https://digitalvillage.io/) | $30,000 |  |  |  ![](https://geps
```suggestion
| [Village Protocol](https://github.com/vechain/grant-program/blob/master/applications/village-protocol.md) | Social Media |  [Website](https://digitalvillage.io/) | $30,000 |  |  | ![](https://geps.dev/progress/0) |
```

2024-03-04 11:52 UTC, gitferry commented
Hey @libotony thanks for your comments. In the last commit ([505b0c4](https://github.com/vechain/grant-program/pull/230/commits/505b0c4a7ee505a35a9add50d08b48cc155ab7e7)) I have changed the Ethereum address that we will use to receive USDT. Is there any change needed for this PR?

2024-03-08 13:43 UTC, libotony commented
> Hey @libotony thanks for your comments. In the last commit ([505b0c4](https://github.com/vechain/grant-program/pull/230/commits/505b0c4a7ee505a35a9add50d08b48cc155ab7e7)) I have changed the Ethereum address that we will use to receive USDT. Is there any change needed for this PR?

Looks good, thanks!

2024-03-08 13:43 UTC, libotony approved these changes

2024-03-08 13:59 UTC, libotony commented on milestone-delivery/deliveries/leaderless_bft_consensus_milestone_1.md
> +* **Milestone Number:** 2
```suggestion
* **Milestone Number:** 1
```

2024-03-08 13:59 UTC, libotony approved these changes

2024-03-08 16:52 UTC, merged

2024-03-08 17:15 UTC, NecoSherry commented
Thank you very much for the delivery! We will proceed with the payment for your application promptly. We appreciate your patience in advance.