Create Milestone Delivery infinitywallet_milestone_1+2.md
vechain/grant-program pull request #231
Opened 2024-02-27 02:27 UTC by InfinityWallet

# Grant Application Checklist

- [X] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] An Ethereum address for the payment of the milestones is provided inside the application.  
- [X] The total funding amount of the project is up to USD $30k for every grant applications.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).

2024-02-27 04:46 UTC, libotony requested changes
Could you kindly separate it into two files, named xxx-milestone_1.md and xxx-milestone_1.md? And also attach the video link you have posted before.

2024-02-27 15:26 UTC, InfinityWallet commented
> Could you kindly separate it into two files, named xxx-milestone_1.md and xxx-milestone_1.md? And also attach the video link you have posted before.

We have split the milestones into 2 files and attached the video link to milestone 2 file

2024-03-08 14:14 UTC, libotony requested changes

2024-03-08 14:14 UTC, libotony commented on milestone-delivery/deliveries/infinitywallet_milestone_1.md
> +* **Milestone Number:** Milestone 1
```suggestion
* **Milestone Number:** 1
```

2024-03-08 14:14 UTC, libotony commented on milestone-delivery/deliveries/infinitywallet_milestone_2.md
> +* **Milestone Number:** Milestone 1 2
```suggestion
* **Milestone Number:** 2
```

2024-03-08 16:47 UTC, arons1 approved these changes

2024-03-11 14:00 UTC, libotony approved these changes

2024-03-11 14:00 UTC, NecoSherry approved these changes

2024-03-11 14:01 UTC, merged

2024-04-17 12:42 UTC, Shazeli99 reviewed
How to use withdrawal accepted gives away