Update miden.md - reordered sequence of milestones
vechain/grant-program pull request #252
Opened 2024-07-09 05:15 UTC by stratisnik

Reordered the sequence of the milestones as recommended by Vechain1, miden-5.md (PR #248)

# Grant Application Checklist

- [ Y] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ Y] An Ethereum address for the payment of the milestones is provided inside the application.  
- [ Y] The total funding amount of the project is up to USD $30k for every grant applications.
- [ Y] The initial PR contains only one commit (squash if needed before submitting your PR).

2024-07-09 05:16 UTC, stratisnik commented
@NecoSherry sequence of milestones updated here for the release of funds.

2024-07-11 06:07 UTC, NecoSherry requested changes

2024-07-11 06:07 UTC, NecoSherry commented on applications/miden.md
>  | Cost | $ 8,000 | $ 3,000 | $ 8,000 | $8,000 | $3,000 | $30,000 |
The cost should align with the milestones.

2024-07-11 06:21 UTC, stratisnik commented
@NecoSherry adjusted as requested

2024-07-18 06:20 UTC, NecoSherry approved these changes

2024-07-24 06:46 UTC, libotony approved these changes

2024-08-09 08:49 UTC, merged