Add ZumoSwap Application
vechain/grant-program pull request #36
Opened 2022-01-07 02:47 UTC by Tinto1024

# Grant Application Checklist

- [x] The [`applications/application-template.md`](../applications/application-template.md) or [`applications/research-template.md`](../applications/research-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] An Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The total funding amount of the project is up to USD $30k for every grant applications.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] If you own an Economic X Node, make sure you have already sent an email([`applications/email-template.md`](../applications/email-template.md)) to grant@vechain.org to claim the additional grant.

2022-01-07 19:47 UTC, 57u requested changes

2022-01-07 19:47 UTC, 57u commented on applications/zumoswap.md
> +We have rented servers and run a VeChain node for data scrapping. We hope the foundation can help us to cover the intial costs, but since 13th month we will earn money and sponsor ourselves.
typo: data scraping

2022-01-07 19:47 UTC, 57u commented on applications/zumoswap.md
> +The working result will be a web page and a set of **open-source Javascript or Python SDKs** for scrapping data. This can largely benefit the VeChain Community.
typo: ...for scraping data.

2022-01-10 04:28 UTC, NecoSherry commented
@Tinto1024 Thank you for your application! Sounds great. We will look into it as soon as possible. 

I had a quick look, and I had a few comments:
1. I noticed that your team members required anonymity. In my option it would be helpful if the evaluators and the committees learnt more about your team. Would it be all right if you sent the team information privately to grant@vechain.org? 

2. Could you format your milestones according to [the application template](https://github.com/vechain/grant-program/blob/master/applications/application-template.md)? 
   - Update the overview table with total funds
   - Update the overview table with full-time equivalent of each milestone. 
   - Table the deliverable of each milestone

3. Would you please update more details about the future operation plan if you have one?

2022-01-13 04:05 UTC, Tinto1024 commented
> @Tinto1024 Thank you for your application! Sounds great. We will look into it as soon as possible.
> 
> I had a quick look, and I had a few comments:
> 
> 1. I noticed that your team members required anonymity. In my option it would be helpful if the evaluators and the committees learnt more about your team. Would it be all right if you sent the team information privately to [grant@vechain.org](mailto:grant@vechain.org)?
> 2. Could you format your milestones according to [the application template](https://github.com/vechain/grant-program/blob/master/applications/application-template.md)?
>    
>    * Update the overview table with total funds
>    * Update the overview table with full-time equivalent of each milestone.
>    * Table the deliverable of each milestone
> 3. Would you please update more details about the future operation plan if you have one?

Total funds: Fixed.
full-time equivalent: Fixed.
Table the deliverable of each milestone: It is already included in the `Details` section.

2022-02-04 13:56 UTC, closed without merging